### ISSUE TITLE
Read of LUX_*_BYTE registers gets duplicate bytes instead of two registers

### ISSUE THREAD

**Issue by 10110111** [bitbank2/max44009#1]
From this line
https://github.com/bitbank2/max44009/blob/f7e864e6da5405392f9bbaa4bf51c2b8b48bda97/max44009.c#L83
I get two identical bytes `XY XY` most of the time instead of the expected `XY 0Z` pattern.

**Comment by bitbank2** [comment]
I've seen some I2C chips use bit 7 of the register address as a "block read" indicator. Can you try changing it to 0x83 for the register and see if that works? If that fails, I guess I can do a separate read for each byte. Please let me know your results.

**Comment by 10110111** [comment]
No, that doesn't work for me, I still get duplicate bytes.
Actually MAX44009 datasheet doesn't describe any transactions where passing only address of `0x03` would lead to reading of both registers `0x03` and `0x04`. Instead it recommends using a _repeated start_ condition before the reads, _each_ preceded by the address of the byte to read. See _Figure 8. Reading Two Registers Consecutively Without a STOP Condition in Between Reads_ in [the datasheet](https://datasheets.maximintegrated.com/en/ds/MAX44009.pdf).
In my implementation I've settled with reading the two bytes separately, since my BCM2835 doesn't appear to support _repeated start_, and I don't feel like bit-banging just for making sure the bytes are consistent (i.e. aren't updated between reads; I try to ensure consistency in another way, [here's the code](https://pastebin.mozilla.org/9075841) if you're interested).

**Comment by bitbank2** [comment]
Thanks for testing it. I don't use Raspberry Pi boards much. On AllWinner boards, the double read works fine. I pushed an update which splits the read into two parts and that should work on all boards now.
